//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace MusicConduct.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool SkipExplicitSongs {
            get {
                return ((bool)(this["SkipExplicitSongs"]));
            }
            set {
                this["SkipExplicitSongs"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool SkipRepeatingSongs {
            get {
                return ((bool)(this["SkipRepeatingSongs"]));
            }
            set {
                this["SkipRepeatingSongs"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("00:00:00")]
        public TimeSpan RepeatingSongsTimespan {
            get {
                return ((TimeSpan)(this["RepeatingSongsTimespan"]));
            }
            set {
                this["RepeatingSongsTimespan"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string Rules {
            get {
                return ((string)(this["Rules"]));
            }
            set {
                this["Rules"] = value;
            }
        }
    }
}
